-- PostgreSQL World Cup Database Dump
-- Generated by World Cup Database Manager

--
-- Name: teams; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.teams (
    team_id integer NOT NULL,
    name character varying(50) NOT NULL
);

--
-- Name: teams_team_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.teams_team_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: teams_team_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.teams_team_id_seq OWNED BY public.teams.team_id;

--
-- Name: games; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.games (
    game_id integer NOT NULL,
    year integer NOT NULL,
    round character varying(50) NOT NULL,
    winner_id integer NOT NULL,
    opponent_id integer NOT NULL,
    winner_goals integer NOT NULL,
    opponent_goals integer NOT NULL
);

--
-- Name: teams team_id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teams ALTER COLUMN team_id SET DEFAULT nextval('public.teams_team_id_seq'::regclass);

--
-- Name: teams teams_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_pkey PRIMARY KEY (team_id);

--
-- Name: teams teams_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_name_key UNIQUE (name);

--
-- Name: games games_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_pkey PRIMARY KEY (game_id);

--
-- Name: games games_winner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_winner_id_fkey FOREIGN KEY (winner_id) REFERENCES public.teams(team_id);

--
-- Name: games games_opponent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_opponent_id_fkey FOREIGN KEY (opponent_id) REFERENCES public.teams(team_id);

--
-- Data for Name: teams; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.teams VALUES (6, 'Argentina');
INSERT INTO public.teams VALUES (3, 'Belgium');
INSERT INTO public.teams VALUES (5, 'Brazil');
INSERT INTO public.teams VALUES (2, 'Croatia');
INSERT INTO public.teams VALUES (4, 'England');
INSERT INTO public.teams VALUES (1, 'France');
INSERT INTO public.teams VALUES (7, 'Germany');
INSERT INTO public.teams VALUES (9, 'Netherlands');
INSERT INTO public.teams VALUES (10, 'Portugal');
INSERT INTO public.teams VALUES (12, 'Russia');
INSERT INTO public.teams VALUES (8, 'Spain');
INSERT INTO public.teams VALUES (11, 'Uruguay');

--
-- Data for Name: games; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.games VALUES (1, 2018, 'Final', 1, 2, 4, 2);
INSERT INTO public.games VALUES (8, 2018, 'Quarter-Final', 4, 10, 2, 0);
INSERT INTO public.games VALUES (5, 2018, 'Quarter-Final', 1, 9, 2, 0);
INSERT INTO public.games VALUES (6, 2018, 'Quarter-Final', 3, 5, 2, 1);
INSERT INTO public.games VALUES (7, 2018, 'Quarter-Final', 2, 12, 2, 2);
INSERT INTO public.games VALUES (3, 2018, 'Semi-Final', 1, 3, 1, 0);
INSERT INTO public.games VALUES (4, 2018, 'Semi-Final', 2, 4, 2, 1);
INSERT INTO public.games VALUES (2, 2018, 'Third Place', 3, 4, 2, 0);
INSERT INTO public.games VALUES (9, 2014, 'Final', 7, 6, 1, 0);
INSERT INTO public.games VALUES (12, 2014, 'Semi-Final', 6, 9, 0, 0);
INSERT INTO public.games VALUES (11, 2014, 'Semi-Final', 7, 5, 7, 1);
INSERT INTO public.games VALUES (10, 2014, 'Third Place', 9, 5, 3, 0);
INSERT INTO public.games VALUES (13, 2010, 'Final', 8, 9, 1, 0);
INSERT INTO public.games VALUES (14, 2010, 'Third Place', 7, 11, 3, 2);
